<?php
/*
 * Copyright (C) 2008-2013 e107 Inc (e107.org), Licensed under GNU GPL (http://www.gnu.org/licenses/gpl.txt)
 *
 * Admin Language File
 *
*/
// Menu
define("LAN_IMA_M_01", "کتابخانه مديا");
define("LAN_IMA_M_02", "مديا اپلود/وارد کردن");
define("LAN_IMA_M_03", "دسته هاي مديا");
define("LAN_IMA_M_04", "ساخت دسته");
define("LAN_IMA_M_05", "اواتار ها");
// Errors / Info / Notices
define("LAN_IMA_001", "مجوز اصلاحش را نداريد.");
define("LAN_IMA_002", "احفظه کافي فعال را براي اين چرخش نداريد");
define("LAN_IMA_003", "چرخش انجام شد");
define("LAN_IMA_004", "تغير اندازه");
// Options
define("LAN_IMA_O_001", "تصاوير خبري");
define("LAN_IMA_O_002", "اخبار [img] bbcode");
define("LAN_IMA_O_003", "صفحه [img] bbcode");
define("LAN_IMA_O_004", "جعبه مخصوص تصاوير");
define("LAN_IMA_O_005", "جعبه مخصوص [img] bbcode");
define("LAN_IMA_O_006", "[img] bbcode");
// Work in progress (Moc)
define("IMALAN_1", "فعالسازي نمايش تصوير");
define("IMALAN_2", "نمايش تصاوير, اين درخواست براي عرض سايت هست (نظرات, چت باکس) براي تصاوير ارسال شده استفاده شود [img] bbcode");
define("IMALAN_3", "روش تغيير اندازه");
define("IMALAN_4", "اين روش استفاده شود براي تغيير اندازه تصاوير, هر يک از GD1/2 کتابخانه, يا جادوي تصوير");
define("IMALAN_5", "مسير براي تصوير جادويي (if selected)");
define("IMALAN_6", "مسير کامل براي تبديل سودمند تصوير جادويي");
define("IMALAN_7", "تنظيمات تصوير");
define("IMALAN_8", "بروزرساني تنظيمات تصوير");
define("IMALAN_9", "تنظيمات  تصوير بروزرساني شد");
define("IMALAN_10", "کلاس نمايش تصوير");
define("IMALAN_11", "محدود کردن کاربراني که مي توانند تصاوير را ببينند (اگر موارد بالا فعال باشد)");
define("IMALAN_12", "غير فعال سازي روش تصوير");
define("IMALAN_13", "اگر نمايش تصوير غير فعال باشد چه مقدار با تصوير همسو باشد");
define("IMALAN_14", "نمايش ادرس تصوير");
define("IMALAN_15", "تصويري نيست");
// define("IMALAN_16", "نمايش اواتارهاي اپلود شده");
// define("IMALAN_17", "کليک کنيد");
define("IMALAN_18", "تصاوير اواتار اپلود شدند");
// define("IMALAN_19", "نمايش 'غيرفعال' پيام");
define("IMALAN_20", "تغيري انجام نشد");
define("IMALAN_21", "استفاده شده توسط");
define("IMALAN_22", "تصويري براي استفاده نيست");
define("IMALAN_23", "اواتار ها");
define("IMALAN_24", "فتوگراف");
define("IMALAN_25", "براي حذف تصاوير استفاده نشده اينجا را کليک کنيد");
define("IMALAN_26", "تصوير(ها) حذف شد(ند)");
define("IMALAN_28", "حذف شد");
define("IMALAN_29", "بدون تصاوير");
// define("IMALAN_30", "همه کس (عمومي)");
// define("IMALAN_31", "فقط مهمانان);
// define("IMALAN_32", "فقط کاربران");
// define("IMALAN_33", "فقط مدير");
//define("IMALAN_34", "فعال سازي تعمير فايل");
//define("IMALAN_35", "قرارگيري PNG-24's  شفاف با  شفافيت الفا در IE 5 / 6 (تاييد ميشود براي عرض سايت)");
define("IMALAN_36", "اندازه اواتار معتبر و دسترسي به ان");
define("IMALAN_37", "معتبرسازي اواتار");
define("IMALAN_38", "بيشترين عرض مجاز");
define("IMALAN_39", "بيشترين ارتفاع مجاز");
define("IMALAN_40", "عرض زياد");
define("IMALAN_41", "ارتفاع زياد");
define("IMALAN_42", "موجود نيست");
// define("IMALAN_43", "حذف اواتار اپلود شده");
// define("IMALAN_44", "حذف ارجاع خارجي");
define("IMALAN_45", "وجود ندارد");
define("IMALAN_46", "بزرگي زياد");
define("IMALAN_47", "مجموع اواتار هاي اپلود شده");
define("IMALAN_48", "مجموع اواتار هاي خارجي");
define("IMALAN_49", "کاربران با اواتار ها");
define("IMALAN_50", "مجموع");
define("IMALAN_51", "اواتار براي ");
define("IMALAN_52", "مسير تصوير جادويي که بطور نادرست وارد شده");
define("IMALAN_53", "مسير براي تصوير جادويي که بصورت درست قرار گرفته, اما اعتباري براي تبديل فايل ممکن نيست");
define("IMALAN_54", "ورژن GD نصب شد:");
define("IMALAN_55", "نصب نشد");
//v0.8
//uploaded avatar list
define("IMALAN_56", "کليک جهت انتخاب");
define("IMALAN_57", "تصوير خيلي بزرگ - براي بزرگتر کردن کليک نماييد");
//avatar check
// define("IMALAN_61", "گزينه ها");
define("IMALAN_62", "دليل");
define("IMALAN_65", "موجود نيست");
define("IMALAN_66", "نام فايل");
define("IMALAN_68", "بستن");
define("IMALAN_69", "پوشه");
define("IMALAN_70", "بدون سيستم پوشه موجود است!");
// define("IMALAN_72", "ايکن ها");
define("IMALAN_73", "کيفيت تصوير کوچک");
define("IMALAN_74", "قرار دهید این را چنانچه کیفیت پایین است بطوریکه امکان تشخیص کیفیت پایین ممکن باشد. بيشترين اندازه 100");
define("IMALAN_75", "عرض اواتار");
define("IMALAN_76", "تصاویر اواتاری که میخواهید اجبارا به این ابعاد باشد (با اندازه پيکسل pixels)");
define("IMALAN_77", "ارتفاع اواتار");
define("IMALAN_78", "عمومي");
define("IMALAN_79", "تغيير اندازه ابعادشان");
define("IMALAN_80", "سايه دار کردن فعال شده ها");
define("IMALAN_81", "همه تصاویر با یک عرض و ارتفاع همکاهنگ میشود این مقدار مشخص در طول مدت تغییر اندازه سایه دار میشود.");
define("IMALAN_82", "نوشته سايه دار");
define("IMALAN_83", "نوشته سايه دار انتخابير");
define("IMALAN_84", "فونت سايه دار");
define("IMALAN_85", "فونت انتخابي سايه دار. اپلود بيشتر .ttf فونت ها به /پوشه فونت ها واقع در دايرکتوري قالب شما");
define("IMALAN_86", "اندازه سايه دار");
define("IMALAN_87", "اندازه فونت در pts");
define("IMALAN_88", "موقعيت سايه دار شدن");
define("IMALAN_89", "سايه دار شدن");
define("IMALAN_90", "حاشيه سايه دار");
define("IMALAN_91", "فاصله اي که سايه بايد از تصوير بگيرد");
define("IMALAN_92", "رنگ سايه دار");
define("IMALAN_93", "رنگي از سايه دار 000000");
define("IMALAN_94", "رنگ سايه قسمت سايه دار");
define("IMALAN_95", "سايه رنگ سايه دار شده به عنوان مثال هست ffffff");
define("IMALAN_96", "تاري قسمت سايه دار");
define("IMALAN_97", "وارد نماييد يک شماره بين 1 تا 100");
define("IMALAN_98", "حساب پيشفرض youtube");
define("IMALAN_99", "استفاده شود از مديا منيجر مرورگر يوتوب.نام حساب خود را وارد نماييد. eg. e107inc");
define("IMALAN_100", "نمايش ويديو هاي وابسته");
define("IMALAN_101", "نمايش اطلاعات ويديو");
define("IMALAN_102", "نمايش عناوين بسته شده بطور پيشفرض");
define("IMALAN_103", "استفاده نسبتا کم علامت تجاري");
define("IMALAN_104", "براي يوتوب يک کد واکنشگراي bbcode بسازيد");
define("IMALAN_105", "تغيير اندازه تصاوير در مدت ورود فايل مديا");
define("IMALAN_106", "خالي گزاشتن براي غير فعال ها");
define("IMALAN_107", "از اطلاعات اپلود نميتواند مسيري تهيه نمايد");
define("IMALAN_108", "نمي تواند انتقال دهد فايل را از [x] به [y]");
define("IMALAN_109", "مسيري دريافت نميکند");
define("IMALAN_110", "مسير");
define("IMALAN_111", "نمي تواند نوع تقليد را بيابد([x]).اپلود خراب شد.");
define("IMALAN_112", "پوشه ([x])  ساخته نشد.");
define("IMALAN_113", "براي مدياي جديد اسکن کنيد (تصاوير, ويديو ها, فايل ها) در پوشه:");
define("IMALAN_114", "مديايي وجود ندارد! لطفا مقداري فايل اپلود نماييد.");
define("IMALAN_115", "عنوان (استفاده داخلي)");
define("IMALAN_116", "عنوان سر (ديدن توسط عموم)");
//define("IMALAN_117", "نويسنده"); // use LAN_AUTHOR
define("IMALAN_118", "نوع تقليد");
define("IMALAN_119", "اندازه فايل");
define("IMALAN_120", "ابعاد");
define("IMALAN_121", "پيشنمايش"); // use LAN_PREVIEW
define("IMALAN_122", "[x] نماش نميتواند تغيير يابد. مجوز فايل را چک کنيد.");
define("IMALAN_123", "ورود به دسته:");
define("IMALAN_124", "ورود به فايل ها");
define("IMALAN_125", "حذف فايل هاي انتخابي");
define("IMALAN_126", "لطفا حداقل يک فايل را چک نماييد.");
define("IMALAN_127", "نميتواند اطلاعات فايل را بگيرد از:");
define("IMALAN_128", "ورودي مديا:");
define("IMALAN_129", "You are about to delete [x] records and <strong>ALL CORRESPONDING FILES</strong>! Please confirm to continue!");
define("IMALAN_130", "صفحه قبلي");
define("IMALAN_131", "صفحه بعدي");
define("IMALAN_132", "برچسب ها/کلمات کليدي");
define("IMALAN_133", "راست پايين");
define("IMALAN_134", "چپ پايين");
define("IMALAN_135", "راست نوک");
define("IMALAN_136", "چپ نوک");
define("IMALAN_137", "وسط");
define("IMALAN_138", "راست");
define("IMALAN_139", "چپ");
define("IMALAN_140", "نوک");
define("IMALAN_141", "پايين");
define("IMALAN_142", "کاشي شده");
define("IMALAN_143", "تصوير");
define("IMALAN_144", "فايل");
define("IMALAN_145", "از کامپيوتر شما");
define("IMALAN_146", "بدون پشتيباني html5.");
define("IMALAN_147", "از طريق اتصال به يک مسير");
define("IMALAN_148", "تصوير/فايل ادرس");
define("IMALAN_149", "شروع اپلود");
define("IMALAN_150", "اپلود يک فايل");
define("IMALAN_151", "انتخاب از کتابخانه");
define("IMALAN_152", "ظهور");
define("IMALAN_153", "بکارگيري در تصوير");
define("IMALAN_154", "عدم استفاده");
define("IMALAN_155", "پيش انتخاب پوشه اواتار");
define("IMALAN_156", "حذف همه تصاوير استفاده نشده");
define("IMALAN_157", "گردش نوشته");
define("IMALAN_158", "حاشيه چپ");
define("IMALAN_159", "حاشيه راست");
define("IMALAN_160", "حاشيه نوک");
define("IMALAN_161", "حاشيه پايين");
define("IMALAN_162", "نمايش داده شود [x] - [y] از تصاوير [z] ");
define("IMALAN_163", "ويديو");
define("IMALAN_164", "حذف ايکن ها از مديا منيجر");
define("IMALAN_165", "تصويري نيست");
define("IMALAN_166", "اپلود تصاوير يا فايل ها");
define("IMALAN_167", "فايلي نيست");
define("IMALAN_168", "کليک روي اواتار براي تغيير ان");
define("IMALAN_169", "اواتاري فعال نيست");
define("IMALAN_170", "انتخاب اين اواتار");
define("IMALAN_171", "فقط مدير توجه نمايد: به پوشه");
define("IMALAN_172", "خاليست. اپلود برخی تصاویر اواتار های پیشفرض به این پوشه برای کاربرانی کهانتخاب می کنند اواتار را از.");
define("IMALAN_173", "مديا مالکي ندارد ");
define("IMALAN_174", "Youtube search requires a (free) YouTube v3 api key.[br]This key is not required unless you wish to perform a keyword, playlist or channel search.[br]Entering a Youtube video URL directly into the box above will still work without having an api key.[br][x]");
define("IMALAN_175", "جستجوي يوتوب. بچسبانيد اينجا ادرس فايل يوتوب را براي مشخص کردن ويديو/پلي ليست/کانال");
define("IMALAN_176", "يک مشکل وجود دارد يک فايل مفقود يا ربايش شده");
define("IMALAN_177", "براي اطلاعات بيشتر اينجا را کليک کنيد براي کليد api");

define("IMALAN_178", "پوشه اواتار ها (قابل انتخاب براي کاربر)");
define("IMALAN_179", "پوشه اواتار ها (شخصي)");


